// You are given two strings s and t.

// String t is generated by random shuffling 
// string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
 let x = t.split("")
    for (let i = 0; i < s.length; i++){
        let a = x.indexOf(s[i])
        x.splice(a,1)
    }
    return x.join("")
};